export enum DocumentStatus {
  COMPLETED = 'completed',
  CORRECT = 'correct',
  CREATED = 'created',
  DECLINED = 'declined',
  DELETED = 'deleted',
  DELIVERED = 'delivered',
  SENT = 'sent',
  SIGNED = 'signed',
  TEMPLATE = 'template',
  TIMEDOUT = 'timedout',
  VOIDED = 'voided',
  UPDATED = 'updated',
  PENDING = 'pending',
  VIEWED = 'viewed',
  REJECTED = 'rejected',
}
